[package]
name = "rsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0"
lazy_static = "*"
serde = "1"
toml = "0"
serde_derive = "1"
colored = "2"
rustyline = "9"
directories = "4"
